<?php

namespace WillCorp\ZombieBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BuildingLevelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BuildingLevelRepository extends EntityRepository
{
}
